[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "SchemeL"

[build]
create-missing = false

[output.html]
mathjax-support = true

[output.html.fold]
enable = true
level = 1
