# This should be purely functional since PRs also use it
name: Scala CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-20.04, windows-latest, macos-latest]
        jdk: [8, 16-ea]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Install SBT
      if: matrix.os == 'macos-latest'
      run: curl -Ls https://git.io/sbt | sudo tee /usr/local/bin/sbt && sudo chmod 0755 /usr/local/bin/sbt # https://github.com/paulp/sbt-extras/
    - name: Disaplay infos
      run: |
        java -version
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ matrix.os }}-${{ matrix.jdk }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Run tests
      run: cd scala/The-Lingo && sbt test
